/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RateCalculatorRouteImport } from './routes/rate-calculator'
import { Route as ManifestRouteImport } from './routes/manifest'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AwbNewRouteImport } from './routes/awb.new'
import { Route as AwbIdRouteImport } from './routes/awb.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RateCalculatorRoute = RateCalculatorRouteImport.update({
  id: '/rate-calculator',
  path: '/rate-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestRoute = ManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AwbNewRoute = AwbNewRouteImport.update({
  id: '/awb/new',
  path: '/awb/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AwbIdRoute = AwbIdRouteImport.update({
  id: '/awb/$id',
  path: '/awb/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/invoices': typeof InvoicesRoute
  '/manifest': typeof ManifestRoute
  '/rate-calculator': typeof RateCalculatorRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/awb/$id': typeof AwbIdRoute
  '/awb/new': typeof AwbNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/invoices': typeof InvoicesRoute
  '/manifest': typeof ManifestRoute
  '/rate-calculator': typeof RateCalculatorRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/awb/$id': typeof AwbIdRoute
  '/awb/new': typeof AwbNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/invoices': typeof InvoicesRoute
  '/manifest': typeof ManifestRoute
  '/rate-calculator': typeof RateCalculatorRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/awb/$id': typeof AwbIdRoute
  '/awb/new': typeof AwbNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/invoices'
    | '/manifest'
    | '/rate-calculator'
    | '/reports'
    | '/settings'
    | '/awb/$id'
    | '/awb/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/invoices'
    | '/manifest'
    | '/rate-calculator'
    | '/reports'
    | '/settings'
    | '/awb/$id'
    | '/awb/new'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/invoices'
    | '/manifest'
    | '/rate-calculator'
    | '/reports'
    | '/settings'
    | '/awb/$id'
    | '/awb/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  InvoicesRoute: typeof InvoicesRoute
  ManifestRoute: typeof ManifestRoute
  RateCalculatorRoute: typeof RateCalculatorRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  AwbIdRoute: typeof AwbIdRoute
  AwbNewRoute: typeof AwbNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-calculator': {
      id: '/rate-calculator'
      path: '/rate-calculator'
      fullPath: '/rate-calculator'
      preLoaderRoute: typeof RateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest': {
      id: '/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof ManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awb/new': {
      id: '/awb/new'
      path: '/awb/new'
      fullPath: '/awb/new'
      preLoaderRoute: typeof AwbNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awb/$id': {
      id: '/awb/$id'
      path: '/awb/$id'
      fullPath: '/awb/$id'
      preLoaderRoute: typeof AwbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  InvoicesRoute: InvoicesRoute,
  ManifestRoute: ManifestRoute,
  RateCalculatorRoute: RateCalculatorRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  AwbIdRoute: AwbIdRoute,
  AwbNewRoute: AwbNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
